version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-catalog
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: catalog
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql


volumes:
  mysql-data:
